checked_by: system-init-agent
last_checked: '2025-07-10 12:21:28'
status:
  ai_trackdown_tools:
    details: CLI available (local)
    status: "\u2705 INSTALLED"
    version: 1.0.0+build.1
  claude_pm_portfolio_manager:
    details: NPM package not found
    status: "\u274C MISSING"
    version: none
  framework_core:
    details: Framework at /Users/masa/Projects/claude-multiagent-pm
    status: "\u2705 INSTALLED"
    version: 4.5.1
  mem0ai:
    details: Service responding
    status: "\u2705 ONLINE"
    version: active
  node_environment:
    details: Node.js available
    status: "\u2705 READY"
    version: v20.19.0
  python_environment:
    details: All required packages available
    status: "\u2705 READY"
    version: Python 3.13.5
