# Development Environment Configuration
# Optimized for development and debugging

environment: "development"
debug_mode: true
config_version: "1.0"
global_enabled: true
max_memory_operations_per_second: 50
auto_reload: true
validation_strict: false  # More lenient for development

# Performance configuration optimized for development
performance:
  create_timeout: 10.0  # Longer timeouts for debugging
  recall_timeout: 5.0
  search_timeout: 15.0
  batch_size: 10  # Smaller batches for easier debugging
  max_concurrent_operations: 3  # Limited concurrency for debugging
  rate_limit_per_second: 50
  
  # Caching disabled for development to see fresh results
  cache_enabled: false
  cache_ttl_seconds: 60
  cache_max_size: 100
  
  max_memory_size_mb: 50  # Smaller memory footprint
  memory_cleanup_threshold: 0.9  # Less aggressive cleanup
  min_memory_quality_score: 0.3  # Lower quality threshold for testing
  max_memories_per_context: 50
  
  # Background processing
  background_processing_enabled: true
  background_queue_size: 100  # Smaller queue for development
  worker_thread_count: 1  # Single thread for easier debugging

# Lifecycle configuration for development
lifecycle:
  default_retention_days: 7  # Short retention for development
  important_memory_retention_days: 30
  error_memory_retention_days: 7
  workflow_memory_retention_days: 14
  
  auto_cleanup_enabled: true
  cleanup_interval_hours: 6  # More frequent cleanup
  cleanup_batch_size: 20
  
  quality_based_cleanup: false  # Disabled for development
  min_quality_for_retention: 0.2
  
  # Archival disabled for development
  archival_enabled: false
  archive_after_days: 30
  archive_backend: null
  
  migration_enabled: false
  migration_schedule: null
  
  compression_enabled: false  # Disabled for easier debugging

# Monitoring configuration for development
monitoring:
  metrics_enabled: true
  metrics_collection_interval: 30  # More frequent collection
  metrics_retention_days: 7  # Short retention
  
  performance_monitoring_enabled: true
  slow_operation_threshold_ms: 2000  # Higher threshold for development
  error_rate_threshold: 0.2  # More tolerant of errors
  
  health_check_enabled: true
  health_check_interval: 60  # Less frequent health checks
  health_check_timeout: 10
  
  # Verbose logging for development
  log_level: "DEBUG"
  log_memory_operations: true
  log_performance_metrics: true
  structured_logging: true
  
  # Alerting disabled for development
  alerting_enabled: false
  alert_channels: []
  error_alert_threshold: 100
  performance_alert_threshold: 5.0

# Backend configuration for development
backend:
  backend_type: "local"  # Use local backend for development
  connection_timeout: 15.0
  read_timeout: 10.0
  write_timeout: 15.0
  max_retries: 2  # Fewer retries for faster feedback
  retry_delay: 0.5
  
  backend_settings:
    local_storage_path: "./dev_memory_storage"
    backup_enabled: false
  
  # Connection pooling disabled for development
  pool_enabled: false
  pool_size: 1
  pool_max_overflow: 0
  
  failover_enabled: false
  failover_backends: []
  
  encryption_enabled: false
  encryption_key_path: null

# Feature toggles for development
features:
  workflow_triggers: true
  agent_triggers: true
  error_triggers: true
  pattern_detection: true
  auto_recall: true
  quality_assessment: false  # Disabled for faster operation
  background_processing: true
  hot_reloading: true

# Development-specific trigger policies
trigger_policies:
  development_workflow:
    enabled: true
    trigger_type: "workflow"
    success_threshold: 0.5  # Lower threshold for testing
    failure_threshold: 0.2
    create_on_success: true
    create_on_failure: true
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.5  # Lower similarity for more matches
    
    min_context_length: 5  # Shorter context for testing
    max_context_length: 5000
    context_required_fields: []
    
    require_quality_validation: false  # Disabled for development
    min_trigger_confidence: 0.3  # Lower confidence threshold
    
    max_triggers_per_minute: 30
    cooldown_period_seconds: 10  # Shorter cooldown for testing
    
    agent_name: null
    agent_trigger_patterns: []
  
  development_agent:
    enabled: true
    trigger_type: "agent"
    success_threshold: 0.6
    failure_threshold: 0.3
    create_on_success: true
    create_on_failure: true
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.6
    
    min_context_length: 5
    max_context_length: 3000
    context_required_fields: ["agent_name"]
    
    require_quality_validation: false
    min_trigger_confidence: 0.4
    
    max_triggers_per_minute: 20
    cooldown_period_seconds: 5
    
    agent_name: null
    agent_trigger_patterns:
      - "error"
      - "exception"
      - "failed"
      - "success"
      - "completed"
  
  development_error:
    enabled: true
    trigger_type: "error"
    success_threshold: 0.0  # N/A for error triggers
    failure_threshold: 0.0  # All errors trigger
    create_on_success: false
    create_on_failure: false
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.8  # High similarity for error patterns
    
    min_context_length: 10
    max_context_length: 2000
    context_required_fields: ["error_type", "error_message"]
    
    require_quality_validation: false
    min_trigger_confidence: 0.7  # Higher confidence for errors
    
    max_triggers_per_minute: 60  # Allow more error triggers
    cooldown_period_seconds: 1  # Short cooldown for errors
    
    agent_name: null
    agent_trigger_patterns:
      - "exception"
      - "traceback"
      - "error"
      - "failed"
      - "timeout"
      - "connection"