# Production Environment Configuration
# Optimized for performance, reliability, and scale

environment: "production"
debug_mode: false
config_version: "1.0"
global_enabled: true
max_memory_operations_per_second: 500
auto_reload: false  # Disabled for production stability
validation_strict: true

# Performance configuration optimized for production
performance:
  create_timeout: 5.0  # Tight timeouts for production SLAs
  recall_timeout: 3.0
  search_timeout: 10.0
  batch_size: 100  # Larger batches for efficiency
  max_concurrent_operations: 20  # High concurrency for scale
  rate_limit_per_second: 500
  
  # Aggressive caching for performance
  cache_enabled: true
  cache_ttl_seconds: 300
  cache_max_size: 2000
  
  max_memory_size_mb: 200  # Larger memory allocation
  memory_cleanup_threshold: 0.75  # Conservative cleanup
  min_memory_quality_score: 0.7  # High quality threshold
  max_memories_per_context: 200
  
  # Full background processing
  background_processing_enabled: true
  background_queue_size: 2000
  worker_thread_count: 8  # Multiple workers for production

# Lifecycle configuration for production
lifecycle:
  default_retention_days: 180  # Longer retention for production data
  important_memory_retention_days: 730  # 2 years for important memories
  error_memory_retention_days: 90  # 3 months for error analysis
  workflow_memory_retention_days: 365  # 1 year for workflow memories
  
  auto_cleanup_enabled: true
  cleanup_interval_hours: 24  # Daily cleanup
  cleanup_batch_size: 200  # Larger cleanup batches
  
  quality_based_cleanup: true
  min_quality_for_retention: 0.6
  
  # Full archival system
  archival_enabled: true
  archive_after_days: 365
  archive_backend: "s3_archive"
  
  migration_enabled: true
  migration_schedule: "0 2 * * 0"  # Weekly at 2 AM Sunday
  
  compression_enabled: true
  compression_after_days: 30

# Monitoring configuration for production
monitoring:
  metrics_enabled: true
  metrics_collection_interval: 60
  metrics_retention_days: 90  # Longer retention for trend analysis
  
  performance_monitoring_enabled: true
  slow_operation_threshold_ms: 500  # Strict performance requirements
  error_rate_threshold: 0.01  # Very low error tolerance
  
  health_check_enabled: true
  health_check_interval: 15  # Frequent health checks
  health_check_timeout: 3
  
  # Production logging configuration
  log_level: "INFO"
  log_memory_operations: false  # Disabled for performance
  log_performance_metrics: false
  structured_logging: true
  
  # Comprehensive alerting
  alerting_enabled: true
  alert_channels: ["production-alerts", "pagerduty", "slack-ops"]
  error_alert_threshold: 5  # Low threshold for production
  performance_alert_threshold: 1.5

# Backend configuration for production
backend:
  backend_type: "mem0"  # Production mem0 backend
  connection_timeout: 5.0
  read_timeout: 3.0
  write_timeout: 5.0
  max_retries: 5  # More retries for production reliability
  retry_delay: 2.0
  
  backend_settings:
    api_key_env: "MEM0_API_KEY_PRODUCTION"
    organization_id: "production_org"
    user_id: "production_user"
    host: "api.mem0.ai"
    timeout: 30
    
  # Robust connection pooling
  pool_enabled: true
  pool_size: 20  # Large pool for production
  pool_max_overflow: 40
  
  # Multi-tier failover
  failover_enabled: true
  failover_backends: ["redis", "local"]
  
  encryption_enabled: true
  encryption_key_path: "/etc/ssl/production_memory_key.pem"

# Feature toggles for production
features:
  workflow_triggers: true
  agent_triggers: true
  error_triggers: true
  pattern_detection: true
  auto_recall: true
  quality_assessment: true
  background_processing: true
  hot_reloading: false  # Disabled for stability

# Production-specific trigger policies
trigger_policies:
  production_workflow:
    enabled: true
    trigger_type: "workflow"
    success_threshold: 0.85  # High threshold for production
    failure_threshold: 0.25
    create_on_success: true
    create_on_failure: true
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.8
    
    min_context_length: 20
    max_context_length: 8000
    context_required_fields: ["workflow_id", "user_id", "environment"]
    
    require_quality_validation: true
    min_trigger_confidence: 0.7
    
    max_triggers_per_minute: 100
    cooldown_period_seconds: 30
    
    agent_name: null
    agent_trigger_patterns: []
  
  production_agent:
    enabled: true
    trigger_type: "agent"
    success_threshold: 0.9  # Very high threshold for production agents
    failure_threshold: 0.2
    create_on_success: true
    create_on_failure: true
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.8
    
    min_context_length: 25
    max_context_length: 5000
    context_required_fields: ["agent_name", "operation", "user_id", "session_id"]
    
    require_quality_validation: true
    min_trigger_confidence: 0.75
    
    max_triggers_per_minute: 50
    cooldown_period_seconds: 20
    
    agent_name: null
    agent_trigger_patterns:
      - "critical_operation"
      - "user_interaction"
      - "business_process"
      - "data_processing"
      - "external_integration"
      - "security_event"
  
  production_error:
    enabled: true
    trigger_type: "error"
    success_threshold: 0.0
    failure_threshold: 0.0
    create_on_success: false
    create_on_failure: false
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.9  # High similarity for error patterns
    
    min_context_length: 50
    max_context_length: 3000
    context_required_fields: ["error_type", "error_message", "stack_trace", "user_id"]
    
    require_quality_validation: true
    min_trigger_confidence: 0.8
    
    max_triggers_per_minute: 20  # Limited to prevent spam
    cooldown_period_seconds: 10
    
    agent_name: null
    agent_trigger_patterns:
      - "system_error"
      - "database_error"
      - "authentication_failure"
      - "authorization_failure"
      - "external_service_error"
      - "timeout_error"
      - "rate_limit_exceeded"
      - "data_corruption"
  
  production_critical_pattern:
    enabled: true
    trigger_type: "pattern"
    success_threshold: 0.95  # Very high threshold for critical patterns
    failure_threshold: 0.1
    create_on_success: true
    create_on_failure: true
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.85
    
    min_context_length: 40
    max_context_length: 2000
    context_required_fields: ["pattern_type", "criticality", "impact"]
    
    require_quality_validation: true
    min_trigger_confidence: 0.9
    
    max_triggers_per_minute: 10  # Limited for critical patterns
    cooldown_period_seconds: 120  # Long cooldown for critical patterns
    
    agent_name: null
    agent_trigger_patterns:
      - "security_threat"
      - "performance_degradation"
      - "data_anomaly"
      - "business_critical_event"
      - "compliance_violation"
      - "system_instability"
  
  production_learning:
    enabled: true
    trigger_type: "success"
    success_threshold: 0.95
    failure_threshold: 0.0
    create_on_success: true
    create_on_failure: false
    create_on_error: false
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.75
    
    min_context_length: 30
    max_context_length: 4000
    context_required_fields: ["learning_type", "knowledge_domain", "quality_score"]
    
    require_quality_validation: true
    min_trigger_confidence: 0.85
    
    max_triggers_per_minute: 15
    cooldown_period_seconds: 60
    
    agent_name: null
    agent_trigger_patterns:
      - "knowledge_synthesis"
      - "pattern_discovery"
      - "successful_resolution"
      - "process_optimization"
      - "user_satisfaction"
      - "efficiency_improvement"
  
  production_context:
    enabled: true
    trigger_type: "context"
    success_threshold: 0.8
    failure_threshold: 0.3
    create_on_success: true
    create_on_failure: true
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.8
    
    min_context_length: 100  # Rich context required
    max_context_length: 10000
    context_required_fields: ["context_type", "session_id", "user_profile"]
    
    require_quality_validation: true
    min_trigger_confidence: 0.7
    
    max_triggers_per_minute: 30
    cooldown_period_seconds: 45
    
    agent_name: null
    agent_trigger_patterns:
      - "session_context"
      - "user_preference"
      - "domain_knowledge"
      - "historical_context"
      - "collaborative_context"