# Testing Environment Configuration
# Optimized for automated testing and CI/CD

environment: "testing"
debug_mode: false
config_version: "1.0"
global_enabled: true
max_memory_operations_per_second: 100
auto_reload: false  # Disabled for consistent test results
validation_strict: true

# Performance configuration optimized for testing
performance:
  create_timeout: 5.0  # Faster timeouts for tests
  recall_timeout: 2.0
  search_timeout: 8.0
  batch_size: 25
  max_concurrent_operations: 5
  rate_limit_per_second: 100
  
  # Caching enabled but with short TTL
  cache_enabled: true
  cache_ttl_seconds: 30
  cache_max_size: 200
  
  max_memory_size_mb: 25  # Limited memory for tests
  memory_cleanup_threshold: 0.7
  min_memory_quality_score: 0.5
  max_memories_per_context: 25
  
  # Background processing limited
  background_processing_enabled: true
  background_queue_size: 50
  worker_thread_count: 2

# Lifecycle configuration for testing
lifecycle:
  default_retention_days: 1  # Very short retention for testing
  important_memory_retention_days: 3
  error_memory_retention_days: 1
  workflow_memory_retention_days: 2
  
  auto_cleanup_enabled: true
  cleanup_interval_hours: 1  # Frequent cleanup for tests
  cleanup_batch_size: 50
  
  quality_based_cleanup: true
  min_quality_for_retention: 0.4
  
  # Archival disabled for testing
  archival_enabled: false
  archive_after_days: 7
  archive_backend: null
  
  migration_enabled: false
  migration_schedule: null
  
  compression_enabled: false  # Disabled for test performance

# Monitoring configuration for testing
monitoring:
  metrics_enabled: true
  metrics_collection_interval: 15  # Frequent for test monitoring
  metrics_retention_days: 1  # Short retention for tests
  
  performance_monitoring_enabled: true
  slow_operation_threshold_ms: 1000
  error_rate_threshold: 0.1
  
  health_check_enabled: true
  health_check_interval: 30
  health_check_timeout: 5
  
  # Minimal logging for test performance
  log_level: "WARNING"
  log_memory_operations: false
  log_performance_metrics: false
  structured_logging: true
  
  # Alerting disabled for testing
  alerting_enabled: false
  alert_channels: []
  error_alert_threshold: 50
  performance_alert_threshold: 3.0

# Backend configuration for testing
backend:
  backend_type: "local"  # Use local backend for test isolation
  connection_timeout: 5.0
  read_timeout: 3.0
  write_timeout: 5.0
  max_retries: 1  # Minimal retries for fast test failure
  retry_delay: 0.1
  
  backend_settings:
    local_storage_path: "./test_memory_storage"
    backup_enabled: false
    cleanup_on_start: true  # Clean storage before tests
  
  # Minimal connection pooling
  pool_enabled: true
  pool_size: 2
  pool_max_overflow: 1
  
  failover_enabled: false
  failover_backends: []
  
  encryption_enabled: false
  encryption_key_path: null

# Feature toggles for testing
features:
  workflow_triggers: true
  agent_triggers: true
  error_triggers: true
  pattern_detection: true
  auto_recall: true
  quality_assessment: true
  background_processing: true
  hot_reloading: false  # Disabled for test stability

# Testing-specific trigger policies
trigger_policies:
  test_workflow:
    enabled: true
    trigger_type: "workflow"
    success_threshold: 0.7
    failure_threshold: 0.4
    create_on_success: true
    create_on_failure: true
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.6
    
    min_context_length: 10
    max_context_length: 2000
    context_required_fields: ["workflow_id"]
    
    require_quality_validation: true
    min_trigger_confidence: 0.5
    
    max_triggers_per_minute: 50
    cooldown_period_seconds: 5
    
    agent_name: null
    agent_trigger_patterns: []
  
  test_agent:
    enabled: true
    trigger_type: "agent"
    success_threshold: 0.8
    failure_threshold: 0.3
    create_on_success: true
    create_on_failure: true
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.7
    
    min_context_length: 10
    max_context_length: 1500
    context_required_fields: ["agent_name", "operation"]
    
    require_quality_validation: true
    min_trigger_confidence: 0.6
    
    max_triggers_per_minute: 30
    cooldown_period_seconds: 2
    
    agent_name: null
    agent_trigger_patterns:
      - "test_passed"
      - "test_failed"
      - "assertion_error"
      - "validation_success"
      - "validation_failure"
  
  test_error:
    enabled: true
    trigger_type: "error"
    success_threshold: 0.0
    failure_threshold: 0.0
    create_on_success: false
    create_on_failure: false
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.9  # High similarity for consistent test errors
    
    min_context_length: 20
    max_context_length: 1000
    context_required_fields: ["error_type", "test_name"]
    
    require_quality_validation: true
    min_trigger_confidence: 0.8
    
    max_triggers_per_minute: 100  # Allow many error triggers in tests
    cooldown_period_seconds: 0  # No cooldown for test errors
    
    agent_name: null
    agent_trigger_patterns:
      - "AssertionError"
      - "ValueError"
      - "TypeError"
      - "TimeoutError"
      - "ConnectionError"
      - "test_failure"
  
  test_pattern:
    enabled: true
    trigger_type: "pattern"
    success_threshold: 0.8
    failure_threshold: 0.2
    create_on_success: true
    create_on_failure: true
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.8
    
    min_context_length: 15
    max_context_length: 1000
    context_required_fields: ["pattern_type"]
    
    require_quality_validation: true
    min_trigger_confidence: 0.7
    
    max_triggers_per_minute: 25
    cooldown_period_seconds: 3
    
    agent_name: null
    agent_trigger_patterns:
      - "repeated_pattern"
      - "anomaly_detected"
      - "performance_pattern"
      - "behavior_pattern"