claude-multiagent-pm:
  agent_id: system-init-agent
  framework_location: /Users/masa/Projects/claude-multiagent-pm
  initialized_at: '2025-07-09 14:05:53'
  mode: multi-project-orchestrator
  version: 4.2.3
dependencies:
  ai-trackdown-tools:
    command: aitrackdown
    package: '@bobmatnyc/ai-trackdown-tools'
    required: true
  claude-pm-portfolio-manager:
    package: '@bobmatnyc/claude-pm-portfolio-manager'
    required: false
  mem0ai:
    health_endpoint: /health
    required: true
    service_url: http://localhost:8002
global_agents:
  auto_discover: true
  load_on_startup: true
  system_trained_path: ./agents/system-trained
  user_defined_path: ./agents/user-defined
templates:
  global_templates_path: ./templates/global
  inheritance_enabled: true
