# Docker/Container Memory Trigger Configuration
# Optimized for containerized deployments with resource constraints

environment: "production"
debug_mode: false
config_version: "1.0"
global_enabled: true
max_memory_operations_per_second: 200
auto_reload: false
validation_strict: true

# Container-optimized performance
performance:
  create_timeout: 4.0
  recall_timeout: 2.5
  search_timeout: 8.0
  batch_size: 50
  max_concurrent_operations: 8  # Limited for container resources
  rate_limit_per_second: 200
  
  # Conservative caching for container memory limits
  cache_enabled: true
  cache_ttl_seconds: 300
  cache_max_size: 1000
  
  max_memory_size_mb: 100  # Container memory limit
  memory_cleanup_threshold: 0.75
  min_memory_quality_score: 0.7
  max_memories_per_context: 100
  
  # Limited background processing for containers
  background_processing_enabled: true
  background_queue_size: 500
  worker_thread_count: 4

# Container-appropriate lifecycle
lifecycle:
  default_retention_days: 90
  important_memory_retention_days: 365
  error_memory_retention_days: 60
  workflow_memory_retention_days: 180
  
  auto_cleanup_enabled: true
  cleanup_interval_hours: 6  # More frequent cleanup for containers
  cleanup_batch_size: 100
  
  quality_based_cleanup: true
  min_quality_for_retention: 0.6
  
  # External archival for containers
  archival_enabled: true
  archive_after_days: 180
  archive_backend: "s3_container"
  
  migration_enabled: false  # Disabled for container stability
  migration_schedule: null
  
  compression_enabled: true
  compression_after_days: 7

# Container monitoring
monitoring:
  metrics_enabled: true
  metrics_collection_interval: 60
  metrics_retention_days: 30
  
  performance_monitoring_enabled: true
  slow_operation_threshold_ms: 1000
  error_rate_threshold: 0.02
  
  health_check_enabled: true
  health_check_interval: 30
  health_check_timeout: 5
  
  log_level: "INFO"
  log_memory_operations: false  # Reduced logging for containers
  log_performance_metrics: false
  structured_logging: true
  
  # Container alerting
  alerting_enabled: true
  alert_channels: ["container-alerts", "prometheus"]
  error_alert_threshold: 10
  performance_alert_threshold: 2.0

# Backend for containers
backend:
  backend_type: "mem0"
  connection_timeout: 5.0
  read_timeout: 3.0
  write_timeout: 5.0
  max_retries: 3
  retry_delay: 1.0
  
  backend_settings:
    api_key_env: "MEM0_API_KEY"
    organization_id_env: "MEM0_ORG_ID"
    user_id_env: "MEM0_USER_ID"
    host: "api.mem0.ai"
    timeout: 30
    
    # Container-specific settings
    connection_pool_size: 10
    keep_alive: true
    retry_on_connection_error: true
  
  # Limited pooling for containers
  pool_enabled: true
  pool_size: 10
  pool_max_overflow: 5
  
  # Simple failover for containers
  failover_enabled: true
  failover_backends: ["local"]
  
  encryption_enabled: true
  encryption_key_path: "/etc/ssl/memory_key.pem"

# Container-appropriate features
features:
  workflow_triggers: true
  agent_triggers: true
  error_triggers: true
  pattern_detection: true
  auto_recall: true
  quality_assessment: true
  background_processing: true
  hot_reloading: false

# Container trigger policies
trigger_policies:
  container_workflow:
    enabled: true
    trigger_type: "workflow"
    success_threshold: 0.8
    failure_threshold: 0.25
    create_on_success: true
    create_on_failure: true
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.75
    
    min_context_length: 25
    max_context_length: 5000
    context_required_fields: ["workflow_id", "container_id", "pod_name"]
    
    require_quality_validation: true
    min_trigger_confidence: 0.7
    
    max_triggers_per_minute: 60
    cooldown_period_seconds: 30
    
    agent_name: null
    agent_trigger_patterns: []
  
  container_error:
    enabled: true
    trigger_type: "error"
    success_threshold: 0.0
    failure_threshold: 0.0
    create_on_success: false
    create_on_failure: false
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.85
    
    min_context_length: 30
    max_context_length: 2000
    context_required_fields: 
      - "error_type"
      - "error_message"
      - "container_id"
      - "pod_name"
      - "namespace"
    
    require_quality_validation: true
    min_trigger_confidence: 0.8
    
    max_triggers_per_minute: 30
    cooldown_period_seconds: 10
    
    agent_name: null
    agent_trigger_patterns:
      - "container_oom"
      - "pod_crash"
      - "health_check_failure"
      - "resource_limit"
      - "network_error"
      - "storage_error"
  
  container_resource:
    enabled: true
    trigger_type: "pattern"
    success_threshold: 0.7
    failure_threshold: 0.4
    create_on_success: false
    create_on_failure: true
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.8
    
    min_context_length: 20
    max_context_length: 1000
    context_required_fields:
      - "resource_type"
      - "usage_percent"
      - "limit_mb"
      - "container_id"
    
    require_quality_validation: true
    min_trigger_confidence: 0.75
    
    max_triggers_per_minute: 20
    cooldown_period_seconds: 60
    
    agent_name: null
    agent_trigger_patterns:
      - "memory_pressure"
      - "cpu_throttling"
      - "disk_pressure"
      - "network_bandwidth"
      - "file_descriptor_limit"