# Enterprise Memory Trigger Configuration
# Production-ready configuration for enterprise deployment

environment: "production"
debug_mode: false
config_version: "1.0"
global_enabled: true
max_memory_operations_per_second: 1000
auto_reload: false
validation_strict: true

# High-performance configuration
performance:
  create_timeout: 3.0
  recall_timeout: 2.0
  search_timeout: 8.0
  batch_size: 200
  max_concurrent_operations: 50
  rate_limit_per_second: 1000
  
  # Aggressive caching for performance
  cache_enabled: true
  cache_ttl_seconds: 600
  cache_max_size: 5000
  
  max_memory_size_mb: 500
  memory_cleanup_threshold: 0.7
  min_memory_quality_score: 0.8
  max_memories_per_context: 500
  
  # Robust background processing
  background_processing_enabled: true
  background_queue_size: 5000
  worker_thread_count: 16

# Enterprise lifecycle management
lifecycle:
  default_retention_days: 365
  important_memory_retention_days: 2555  # 7 years
  error_memory_retention_days: 180
  workflow_memory_retention_days: 730
  
  auto_cleanup_enabled: true
  cleanup_interval_hours: 12
  cleanup_batch_size: 500
  
  quality_based_cleanup: true
  min_quality_for_retention: 0.7
  
  # Enterprise archival
  archival_enabled: true
  archive_after_days: 730
  archive_backend: "s3_enterprise"
  
  migration_enabled: true
  migration_schedule: "0 1 * * 0"  # Weekly at 1 AM
  
  compression_enabled: true
  compression_after_days: 90

# Comprehensive monitoring
monitoring:
  metrics_enabled: true
  metrics_collection_interval: 30
  metrics_retention_days: 180
  
  performance_monitoring_enabled: true
  slow_operation_threshold_ms: 200
  error_rate_threshold: 0.005
  
  health_check_enabled: true
  health_check_interval: 10
  health_check_timeout: 2
  
  log_level: "INFO"
  log_memory_operations: false
  log_performance_metrics: false
  structured_logging: true
  
  # Enterprise alerting
  alerting_enabled: true
  alert_channels: 
    - "pagerduty-critical"
    - "slack-ops-alerts" 
    - "email-oncall"
    - "datadog-alerts"
  error_alert_threshold: 3
  performance_alert_threshold: 1.2

# Enterprise backend configuration
backend:
  backend_type: "mem0"
  connection_timeout: 3.0
  read_timeout: 2.0
  write_timeout: 3.0
  max_retries: 5
  retry_delay: 2.0
  
  backend_settings:
    api_key_env: "MEM0_API_KEY_PRODUCTION"
    organization_id: "enterprise_org_id"
    user_id: "enterprise_user_id"
    host: "api.mem0.ai"
    timeout: 30
    
    # Enterprise-specific settings
    region: "us-east-1"
    encryption_at_rest: true
    audit_logging: true
    compliance_mode: "SOC2"
    data_residency: "US"
  
  # Robust connection pooling
  pool_enabled: true
  pool_size: 50
  pool_max_overflow: 100
  
  # Multi-tier failover
  failover_enabled: true
  failover_backends: ["redis_cluster", "postgresql_backup", "local_emergency"]
  
  encryption_enabled: true
  encryption_key_path: "/etc/ssl/certs/enterprise_memory_key.pem"

# All features enabled for enterprise
features:
  workflow_triggers: true
  agent_triggers: true
  error_triggers: true
  pattern_detection: true
  auto_recall: true
  quality_assessment: true
  background_processing: true
  hot_reloading: false  # Disabled for production stability

# Enterprise trigger policies
trigger_policies:
  enterprise_workflow:
    enabled: true
    trigger_type: "workflow"
    success_threshold: 0.9
    failure_threshold: 0.15
    create_on_success: true
    create_on_failure: true
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.85
    
    min_context_length: 50
    max_context_length: 15000
    context_required_fields: 
      - "workflow_id"
      - "user_id" 
      - "session_id"
      - "organization_id"
      - "environment"
      - "version"
    
    require_quality_validation: true
    min_trigger_confidence: 0.8
    
    max_triggers_per_minute: 200
    cooldown_period_seconds: 60
    
    agent_name: null
    agent_trigger_patterns: []
  
  enterprise_agent:
    enabled: true
    trigger_type: "agent"
    success_threshold: 0.95
    failure_threshold: 0.1
    create_on_success: true
    create_on_failure: true
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.85
    
    min_context_length: 30
    max_context_length: 8000
    context_required_fields:
      - "agent_name"
      - "operation"
      - "user_id"
      - "session_id"
      - "organization_id"
      - "business_unit"
    
    require_quality_validation: true
    min_trigger_confidence: 0.85
    
    max_triggers_per_minute: 100
    cooldown_period_seconds: 30
    
    agent_name: null
    agent_trigger_patterns:
      - "enterprise_integration"
      - "customer_interaction"
      - "business_process"
      - "compliance_check"
      - "audit_event"
      - "security_validation"
  
  enterprise_error:
    enabled: true
    trigger_type: "error"
    success_threshold: 0.0
    failure_threshold: 0.0
    create_on_success: false
    create_on_failure: false
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.95
    
    min_context_length: 100
    max_context_length: 5000
    context_required_fields:
      - "error_type"
      - "error_message"
      - "stack_trace"
      - "user_id"
      - "session_id"
      - "service_name"
      - "severity"
    
    require_quality_validation: true
    min_trigger_confidence: 0.9
    
    max_triggers_per_minute: 50
    cooldown_period_seconds: 15
    
    agent_name: null
    agent_trigger_patterns:
      - "security_incident"
      - "data_breach"
      - "service_outage"
      - "compliance_violation"
      - "authentication_failure"
      - "authorization_error"
      - "data_corruption"
      - "integration_failure"
  
  enterprise_business_critical:
    enabled: true
    trigger_type: "pattern"
    success_threshold: 0.98
    failure_threshold: 0.05
    create_on_success: true
    create_on_failure: true
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.9
    
    min_context_length: 100
    max_context_length: 20000
    context_required_fields:
      - "business_event_type"
      - "impact_level"
      - "stakeholders"
      - "financial_impact"
      - "compliance_tags"
    
    require_quality_validation: true
    min_trigger_confidence: 0.95
    
    max_triggers_per_minute: 25
    cooldown_period_seconds: 300  # 5 minutes for critical events
    
    agent_name: null
    agent_trigger_patterns:
      - "revenue_impact"
      - "customer_churn"
      - "regulatory_event"
      - "strategic_decision"
      - "merger_acquisition"
      - "product_launch"
      - "market_shift"
  
  enterprise_learning:
    enabled: true
    trigger_type: "success"
    success_threshold: 0.95
    failure_threshold: 0.0
    create_on_success: true
    create_on_failure: false
    create_on_error: false
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.8
    
    min_context_length: 200
    max_context_length: 10000
    context_required_fields:
      - "learning_domain"
      - "knowledge_type"
      - "business_value"
      - "expertise_level"
      - "validation_score"
    
    require_quality_validation: true
    min_trigger_confidence: 0.9
    
    max_triggers_per_minute: 50
    cooldown_period_seconds: 120
    
    agent_name: null
    agent_trigger_patterns:
      - "best_practice_discovery"
      - "process_optimization"
      - "innovation_insight"
      - "competitive_advantage"
      - "efficiency_improvement"
      - "risk_mitigation"
      - "cost_reduction"
  
  enterprise_compliance:
    enabled: true
    trigger_type: "pattern"
    success_threshold: 0.99
    failure_threshold: 0.01
    create_on_success: true
    create_on_failure: true
    create_on_error: true
    
    pattern_detection_enabled: true
    pattern_similarity_threshold: 0.95
    
    min_context_length: 150
    max_context_length: 25000
    context_required_fields:
      - "compliance_framework"
      - "regulation_type"
      - "audit_trail"
      - "risk_level"
      - "remediation_required"
    
    require_quality_validation: true
    min_trigger_confidence: 0.98
    
    max_triggers_per_minute: 10
    cooldown_period_seconds: 600  # 10 minutes for compliance events
    
    agent_name: null
    agent_trigger_patterns:
      - "GDPR_event"
      - "SOX_compliance"
      - "HIPAA_violation"
      - "PCI_DSS_event"
      - "SOC2_audit"
      - "ISO27001_event"
      - "regulatory_reporting"