# Minimal Memory Trigger Configuration
# Simplest possible configuration for getting started

environment: "development"
global_enabled: true
config_version: "1.0"

# Basic performance settings
performance:
  create_timeout: 5.0
  recall_timeout: 3.0
  batch_size: 10
  max_concurrent_operations: 2
  cache_enabled: false

# Local backend for simplicity
backend:
  backend_type: "local"
  backend_settings:
    local_storage_path: "./memory_storage"

# Minimal lifecycle settings
lifecycle:
  default_retention_days: 7
  auto_cleanup_enabled: true
  cleanup_interval_hours: 24

# Basic monitoring
monitoring:
  metrics_enabled: false
  log_level: "INFO"
  alerting_enabled: false

# Enable core features only
features:
  workflow_triggers: true
  agent_triggers: false
  error_triggers: true
  pattern_detection: false
  auto_recall: false
  quality_assessment: false
  background_processing: false
  hot_reloading: true

# Single basic trigger policy
trigger_policies:
  basic_workflow:
    enabled: true
    trigger_type: "workflow"
    success_threshold: 0.7
    failure_threshold: 0.3
    create_on_success: true
    create_on_failure: true
    create_on_error: true
    
    pattern_detection_enabled: false
    require_quality_validation: false
    
    min_context_length: 10
    max_context_length: 1000
    max_triggers_per_minute: 10
    cooldown_period_seconds: 30