#!/bin/bash
# Claude PM Framework - MCP Service Installation
# Generated by deployment script v4.5.1

echo "Installing recommended MCP services..."
echo "========================================"


echo "Installing MCP-Zen..."
if npx @modelcontextprotocol/server-zen; then
    echo "✓ MCP-Zen installed successfully"
else
    echo "⚠ Warning: Failed to install MCP-Zen"
fi
echo


echo "========================================"
echo "MCP service installation completed"
echo
echo "Next steps:"
echo "1. Configure services in your Claude settings"
echo "2. Restart Claude to load new services" 
echo "3. The orchestrator will auto-detect available services"
