# GitHub API Integration Configuration for Claude PM Framework
# This file contains configuration settings for syncing Claude PM trackdown tickets to GitHub Issues

# GitHub API Settings
github:
  api_version: "2022-11-28"
  base_url: "https://api.github.com"
  rate_limit:
    requests_per_hour: 5000
    warning_threshold: 100
    critical_threshold: 10
    backoff_strategy: "exponential"
    max_retries: 5

# Repository Settings
repository:
  default_owner: "bobmatnyc"  # From .env file
  required_permissions:
    - "issues"
    - "metadata" 
    - "projects"
    - "pull_requests"

# Sync Configuration
sync:
  default_direction: "claude_pm_to_github"
  conflict_resolution: "claude_pm_wins"
  backup_enabled: true
  backup_retention_days: 30
  
  # Batch processing
  batch_size: 50
  concurrent_requests: 3
  request_delay_ms: 100

# Label Configuration
labels:
  # Priority labels
  priority:
    critical:
      color: "B60205"
      description: "Critical priority task"
    high:
      color: "D93F0B" 
      description: "High priority task"
    medium:
      color: "FBCA04"
      description: "Medium priority task"
    low:
      color: "0E8A16"
      description: "Low priority task"
  
  # Type labels
  type:
    memory:
      color: "5319E7"
      description: "Memory/AI related task"
    epic:
      color: "8B5CF6"
      description: "Epic tracking"
    integration:
      color: "5319E7"
      description: "Integration task"
    infrastructure:
      color: "0052CC"
      description: "Infrastructure task"
    cross_project:
      color: "F59E0B"
      description: "Cross-project task"
  
  # Milestone labels
  milestone:
    foundation:
      color: "C5DEF5"
      description: "M01 Foundation milestone"
    automation:
      color: "BFD4F2"
      description: "M02 Automation milestone"
    orchestration:
      color: "D4C5F9"
      description: "M03 Orchestration milestone"
  
  # Epic labels
  epic:
    fep_001:
      color: "F9D0C4"
      description: "Framework Infrastructure Setup"
    fep_002:
      color: "FEF2C0"
      description: "Multi-Agent Coordination Patterns"
    fep_003:
      color: "C5DEF5"
      description: "Advanced Workflow Automation"
    fep_004:
      color: "D4C5F9"
      description: "Enterprise Orchestration Patterns"
    fep_007:
      color: "F9D0C4"
      description: "Claude Max + mem0AI Enhanced Architecture"
    fep_008:
      color: "FEF2C0"
      description: "Memory-Augmented Agent Ecosystem"
    fep_009:
      color: "C5DEF5"
      description: "Intelligent Task Decomposition System"
    fep_010:
      color: "D4C5F9"
      description: "Continuous Learning Engine"
  
  # Status labels
  status:
    blocked:
      color: "E99695"
      description: "Task is blocked"
    completed:
      color: "0E8A16"
      description: "Task completed"
    claude_pm_sync:
      color: "7057FF"
      description: "Synced from Claude PM Framework"

# Milestone Configuration
milestones:
  m01_foundation:
    title: "M01 Foundation"
    description: "Critical Infrastructure - Framework foundation and project organization"
    due_date: "2025-08-01T00:00:00Z"
    state: "open"
  
  m02_automation:
    title: "M02 Automation"
    description: "Workflow Systems - Multi-agent coordination and memory integration"
    due_date: "2025-09-01T00:00:00Z"
    state: "open"
  
  m03_orchestration:
    title: "M03 Orchestration"
    description: "Advanced Systems - Enterprise orchestration and learning systems"
    due_date: "2025-10-01T00:00:00Z"
    state: "open"

# Ticket Mapping Rules
ticket_mapping:
  # Epic assignments based on ticket ID prefixes
  epic_mapping:
    "MEM-": "FEP-007"
    "M01-": "FEP-001"
    "M02-": "FEP-002"
    "M03-": "FEP-004"
    "FEP-": "self"  # FEP tickets are their own epics
    "CPT-": "FEP-003"
    "INT-": "FEP-002"
    "INF-": "FEP-001"
  
  # Milestone assignments
  milestone_mapping:
    "M01-": "M01 Foundation"
    "MEM-001": "M01 Foundation"
    "MEM-002": "M01 Foundation"
    "MEM-003": "M01 Foundation"
    "MEM-004": "M02 Automation"
    "MEM-005": "M02 Automation"
    "M02-": "M02 Automation"
    "INT-": "M02 Automation"
    "MEM-006": "M03 Orchestration"
    "M03-": "M03 Orchestration"
    "INF-": "M03 Orchestration"
    "default": "M01 Foundation"
  
  # Priority assignments
  priority_mapping:
    "MEM-001": "CRITICAL"
    "MEM-002": "CRITICAL"
    "MEM-003": "CRITICAL"
    "MEM-004": "HIGH"
    "MEM-005": "HIGH"
    "M01-": "HIGH"
    "MEM-006": "MEDIUM"
    "M02-": "MEDIUM"
    "INT-": "MEDIUM"
    "CPT-": "MEDIUM"
    "M03-": "LOW"
    "INF-": "LOW"
    "default": "MEDIUM"
  
  # Story point estimates
  story_points:
    known_tickets:
      "MEM-001": 8
      "MEM-002": 5
      "MEM-003": 13
      "MEM-004": 8
      "MEM-005": 8
      "MEM-006": 10
    
    default_by_prefix:
      "M01-": 3
      "M02-": 5
      "M03-": 8
      "FEP-": 21
      "INT-": 5
      "INF-": 3
      "CPT-": 2
      "default": 3

# File Paths
paths:
  backlog: "/Users/masa/Projects/Claude-PM/trackdown/BACKLOG.md"
  sync_log: "/Users/masa/Projects/Claude-PM/sync/github_sync_log.json"
  backup_dir: "/Users/masa/Projects/Claude-PM/backups"
  log_dir: "/Users/masa/Projects/Claude-PM/logs"
  env_file: "/Users/masa/Projects/Claude-PM/.env"

# Issue Template
issue_template:
  body_format: |
    **Claude PM Ticket:** {ticket_id}
    **Priority:** {priority}
    **Story Points:** {story_points}
    **Milestone:** {milestone}
    **Status:** {status}
    {epic_line}
    {dependencies_line}
    {completion_date_line}
    
    ## Description
    {description}
    
    ---
    *This issue was automatically synced from Claude PM Framework at {sync_timestamp}*
    *Backlog location: `/Users/masa/Projects/Claude-PM/trackdown/BACKLOG.md`*
  
  title_format: "[{ticket_id}] {title}"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_file_size_mb: 100
  backup_count: 5
  console_output: true
  
  # Log levels by component
  component_levels:
    "github_sync.GitHubAPIClient": "INFO"
    "github_sync.RateLimitHandler": "WARNING"
    "github_sync.TicketParser": "INFO"
    "github_sync.ClaudePMGitHubSync": "INFO"