#!/bin/bash
# Claude PM Framework - Health Check
# Generated by deployment script v4.5.1

echo "🔍 Claude PM Framework Health Check"
echo "======================================"

cd "/Users/masa/Projects/claude-multiagent-pm"

# Check framework core
if [ -d "claude_pm" ]; then
    echo "✓ Framework core present"
else
    echo "❌ Framework core missing"
    exit 1
fi

# Check CLI wrappers
if [ -x "bin/aitrackdown" ]; then
    echo "✓ aitrackdown CLI available"
else
    echo "❌ aitrackdown CLI missing"
    exit 1
fi

# Check configuration
if [ -f ".claude-pm/config.json" ]; then
    echo "✓ Deployment configuration present"
else
    echo "❌ Deployment configuration missing"
    exit 1
fi

# Test AI-trackdown functionality
if ./bin/aitrackdown status >/dev/null 2>&1; then
    echo "✓ AI-trackdown integration working"
else
    echo "⚠ AI-trackdown integration issue"
fi

# Check Python environment
if python3 --version >/dev/null 2>&1; then
    echo "✓ Python environment ready"
else
    echo "❌ Python environment issue"
    exit 1
fi

echo "======================================"
echo "🎉 Health check completed successfully"
