name: test-project
description: "AI-Trackdown general project: test-project"
version: 1.0.0
tasks_directory: tasks
structure:
  epics_dir: epics
  issues_dir: issues
  tasks_dir: tasks
  templates_dir: templates
naming_conventions:
  epic_prefix: EP
  issue_prefix: ISS
  task_prefix: TSK
  file_extension: .md
default_assignee: masa
ai_context_templates:
  - context/requirements
  - context/constraints
  - context/assumptions
  - context/dependencies
automation:
  auto_update_timestamps: true
  auto_calculate_tokens: false
  auto_sync_status: true
github_sync:
  enabled: true
  repository: bobmatnyc/ai-presidential-study
  token: ${GITHUB_TOKEN:-""}
  auto_sync: true
  conflict_resolution: most_recent
  sync_labels: true
  sync_milestones: true
  sync_assignees: true
  batch_size: 50
  rate_limit_delay: 100
